---
- name: Ensure yum-utils is installed
  yum:
    update_cache: yes
    state: present
    name: "yum-utils"

- name: Run "yum update"
  yum:
    update_cache: yes
    name: "*"

- name: Check if reboot is required.
  command: needs-restarting -r
  failed_when: false
  register: reboot_required
  changed_when: false

- debug:
    msg: "Reboot is required!!!"
  when: reboot_required.rc != 0

- name: Reboot host(s).
  include_role:
    name: reboot_host
  when: reboot_required.rc != 0 and reboot_ok
